name: materials-concepts
channels:
  - conda-forge
dependencies:
  - pandas
  - click
  - nltk
  - rake_nltk
  - fire
  - langdetect
  - scipy
  - networkx
  - pyarrow
  - hatchling
  - requests
  - loguru

